### ISSUE TITLE
Повторный вход в аккаунт не работает

### ISSUE THREAD

**Issue by SemyonMakhaev** [urfu-2016/team2#135]
1. Вошёл
2. Вышел
3. Пытаюсь войти
Результат: не получается

**Comment by FoKycHuK** [comment]
в хероку не воспроизводится. попробуй повходить-выходить вот с этими креденшлами:
логин: huj
пароль: qweqwe

**Comment by SemyonMakhaev** [comment]
Дропнули базу, заработало
